/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomisma;

/**
 *
 * @author Chunmeista
 */
public class TransactionItem extends javax.swing.JPanel {

    /**
     * Creates new form TransactionItem
     */
    public TransactionItem(String bal, String descrip) {
        initComponents();
        this.transaction_balance.setText(bal);
        this.transaction_description.setText(descrip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transaction_balance = new javax.swing.JLabel();
        transaction_description = new javax.swing.JLabel();
        transaction_description1 = new javax.swing.JLabel();

        transaction_balance.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        transaction_balance.setText("$0.00");

        transaction_description.setText("transaction_description");

        transaction_description1.setText("transaction_type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transaction_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transaction_description, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transaction_description1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(transaction_description)
                .addComponent(transaction_description1))
            .addComponent(transaction_balance)
        );

        transaction_description1.getAccessibleContext().setAccessibleName("transaction_type");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel transaction_balance;
    private javax.swing.JLabel transaction_description;
    private javax.swing.JLabel transaction_description1;
    // End of variables declaration//GEN-END:variables
}
